config/routes.rb
Rails.application.routes.draw do
  root 'session#new'

  get 'appointments/new_week', :to => 'appointments#new_week'
  resources :session, :only => [:new, :create, :destroy]
  resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  validates :start_time, presence: true, uniqueness: { scope: :date }
  validates :end_time, presence: true, uniqueness: { scope: :date }
  validates :date, presence: true
  validates :user, presence: true
  validate :check_for_date_and_time_overlap
  validate :date_is_not_before_today
  validate :end_time_is_after_start

  def check_for_date_and_time_overlap
    days_events = Appointment.where(date: date)
    if days_events.length > 0
      days_events.each do |event|
        if (start_time...end_time).overlaps?(event.start_time...event.end_time)
          errors.add(:time, "overlaps with another appointment")
        end
      end
    end 
  end

  def date_is_not_before_today
    if date && date < Date.today
        errors.add(:date, "is before today")
      end
  end

  def end_time_is_after_start
    if end_time && start_time && end_time < start_time
      errors.add(:end_time, "is invalid")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @user = User.find_by_id(session[:user_id])
    if @user
      @appointments = Appointment.all
      @weekdays = Date.today.all_week.to_a[0..4]
    else
      redirect_to controller: :session, action: :new
    end
  end

  def new
    @user = User.find_by_id(session[:user_id])
    if @user
      render :new
    else
      redirect_to controller: :session, action: :new
    end
  end

  def create
    @user = User.find_by_id(session[:user_id])
    @appointment = Appointment.new(
      date: params[:appointment][:date], 
      start_time: params[:appointment][:start_time], 
      end_time: params[:appointment][:end_time], 
      user_id: @user.id
    )
    if @appointment.save
      redirect_to appointments_path
    else
      @message = @appointment.errors.messages
      render :new
    end
  end

  def show

  end
  def new_week
    @user = User.find_by_id(session[:user_id])
    @weekdays = (Date.today + params[:week].to_i.week).all_week.to_a[0..4]
    @appointments = Appointment.all
    render partial: "calendar", locals: {appointments: @appointments} 
  end
  def update_week_scroll
    render partial: "week_scroll"
    r
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    redirect_to controller: :appointments, action: :index if session[:user_id] 
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to controller: :appointments, action: :index
    else
      @message = 'Incorrect Email & Password Combination'
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_appointment.html.haml
- @weekdays.each do |day|
  .day{:class => "color-#{@weekdays.index(day) % 2}"}
    .day-label{:id => day}
      = day.strftime("%A")[0..2]
      = day.to_s.split('-')[1..2].join('/').remove(/\A0/).gsub(/\D(0)/, '/')
      - @appointments.each do |appointment|
        - if appointment.date == day
          .appointment 
            .user
              = @user.first_name
            .start_time
              = appointment.start_time
            .end_time
              = appointment.end_time

app/views/appointments/_calendar.html.haml
- @weekdays.each do |day|
  .day{:class => "color-#{@weekdays.index(day) % 2}"}
    .day-label{:id => day}
      = day.strftime("%A")[0..2]
      = day.to_s.split('-')[1..2].join('/').remove(/\A0/).gsub(/\D(0)/, '/')
    - @appointments.each do |appointment|
      - if appointment.date == day
        - position = ((appointment.start_time.strftime("%k%M").to_i - 800)/100 * 76 +13)
        .appointment{:style => "margin-top:#{position}px"} 
          .time
            = (appointment.start_time.strftime("%l:%M %p -") + appointment.end_time.strftime("%l:%M %p")).remove(/:+0{2}/)
          .user
            = @user.first_name

app/views/appointments/_week_scroll.html.haml
= (@weekdays[0].strftime("%B %d ") + @weekdays[4].strftime("- %d")).gsub(/\D0/, " ")
%span#year
  = @weekdays[4].strftime(" %Y")

app/views/appointments/index.html.haml
.nav-bar
  = image_tag "small_logo_fish.png", class: "small_logo"
  .logout
    = link_to "Sign Out", session_path(@user), :method => :delete
  = button_to "Book the Fishbowl", new_appointment_path, class: "button primary", id: "book-fishbowl", method: :get
.week-scroll
  .js-prev-week
  .week-scroll-display
    = render partial: 'week_scroll'
  .js-next-week
.calendar
  .times
    %ul 
      %li
        %span
          8 AM
      %li
        %span
          9 AM
      %li
        %span
          10 AM
      %li
        %span
          11 AM
      %li
        %span
          12 PM
      %li
        %span
          1 PM
      %li
        %span
          2 PM
      %li
        %span
          3 PM
      %li
        %span
          4 PM
      %li
        %span
          5 PM
      %li
        %span
          6 PM
      %li
        %span
          7 PM
      %li
        %span
          8 PM
  .dates
    = render partial: "calendar"

  

app/views/appointments/new.html.haml
.nav-bar
  = link_to root_path do
    = image_tag "small_logo_fish.png", class: "small_logo"
  .logout
    = link_to "Sign Out", session_path(@user), :method => :delete
.main
  .container
    .swimming-fish
      = image_tag "fish_2.png"
    .booking
      %h1 Book the Fishbowl
      - if @message
        .errors
          - @message.each_pair do |message|
            .error
              %p  
                = message.join(" ")

      = form_for :appointment, :url => {:controller => 'appointments', :action => 'create'} do |f|
        = f.label :date
        = f.date_field :date
        = f.label :start_time 
        = f.time_field :start_time
        = f.label :end_time
        = f.time_field :end_time
        = f.submit 'Save', class: "button primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlassBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield %>

</body>
</html>

app/views/session/new.html.haml
.session-new
  .content
    .header
      %h1 
        DevShop&apos;s 
        %span
          FishBowl
        Scheduler

    .errors
      = @message
    .login-wrapper
      .fishbowl
        = image_tag "fishbowl.png"
      .login
        = form_for :session, :url => {:controller => 'session', :action => 'create'} do |f|
          = f.label :email 
          = f.text_field :email

          = f.label :password
          = f.password_field :password

          = f.submit 'Log in', class: "secondary"